In [1]:
import pymysql
    # Establish the connection
connection = pymysql.connect(
        host="localhost",
        port=3306,
        user="root",
        password="priya"
    
    )
cursor = connection.cursor()
print("Connected")

Connected

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("final_data_food.csv")

In [4]:
from sqlalchemy import create_engine
engine = create_engine(
    'mysql+pymysql://root:priya@localhost:3306/food_delivery_db'
)

In [5]:
cursor.execute("SELECT * FROM food_delivery_db.delivery_table");
results = cursor.fetchall()
results = pd.DataFrame(results)
results

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,ORD000001,CUST6948,19,Male,Hyderabad,Central,RES936,Restaurant_29,Chinese,2024-10-20 00:00:00,...,DP563,5,4.4,Weekend,1,0.13,Sunday,0.006086,Delayed,NaN
1,ORD000002,CUST6515,44,Female,Chennai,North,RES689,Restaurant_419,Chinese,2024-08-12 00:00:00,...,DP369,5,4.7,Weekday,1,0.48,Monday,0.009899,On-Time Delivery,Middle-Aged
2,ORD000003,CUST1765,46,Male,Delhi,South,RES723,Restaurant_244,Arabian,2024-12-08 00:00:00,...,DP580,4,4.9,Weekend,1,0.08,Sunday,0.010855,Delayed,Middle-Aged
3,ORD000004,CUST2744,40,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,2024-10-08 00:00:00,...,DP155,0,3.4,Weekday,1,0.00,Tuesday,0.000000,Delayed,Middle-Aged
4,ORD000005,CUST4389,57,Female,Chennai,South,RES419,Restaurant_262,Chinese,2024-02-04 00:00:00,...,DP728,2,4.4,Weekend,0,0.12,Sunday,0.034091,On-Time Delivery,Seniors
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32681,ORD032682,CUST4853,44,Male,Hyderabad,Central,RES116,Restaurant_229,Italian,2024-07-14 00:00:00,...,DP813,5,4.2,Weekend,1,0.46,Sunday,0.023279,Delayed,Middle-Aged
32682,ORD032683,CUST6120,36,Female,Delhi,South,RES820,Restaurant_461,Indian,2024-06-03 00:00:00,...,DP965,2,4.7,Weekday,1,0.47,Monday,0.073783,Delayed,Adults
32683,ORD032684,CUST2119,26,Male,Delhi,South,RES922,Restaurant_90,Italian,2024-02-13 00:00:00,...,DP102,2,3.9,Weekday,1,0.08,Tuesday,0.001613,Delayed,Young Adults
32684,ORD032685,CUST2893,39,Other,Mumbai,South,RES789,Restaurant_31,Indian,2024-06-08 00:00:00,...,DP348,0,3.1,Weekend,0,0.00,Saturday,0.000000,Delayed,Adults
32685,ORD032686,CUST9817,42,Female,Hyderabad,North,RES683,Restaurant_433,Indian,2024-10-13 00:00:00,...,DP512,2,3.9,Weekend,0,0.28,Sunday,0.011382,On-Time Delivery,Middle-Aged

Analyst Tasks (EDA & Analytics)

1. Identify top spending customers

In [6]:
cursor.execute("""SELECT customer_id, sum(final_amount) AS total_spent
               FROM food_delivery_db.delivery_table
               GROUP BY customer_id
               ORDER BY total_spent Desc
               LIMIT 10;""")
Q1_results = cursor.fetchall()
Q1_results = pd.DataFrame(Q1_results, columns=['cutomer_id','total_spent'])
Q1_results

  cutomer_id  total_spent
0   CUST7320      28497.0
1   CUST5957      27909.0
2   CUST8160      27843.0
3   CUST1821      26833.0
4   CUST4185      26513.0
5   CUST5803      26446.5
6   CUST9395      26339.0
7   CUST5417      26071.0
8   CUST9748      25397.0
9   CUST5208      25357.5

2. Analyze age group vs order value

In [7]:
cursor.execute("""SELECT customer_age_group, AVG(final_amount) AS avg_order_value 
               FROM food_delivery_db.delivery_table 
               GROUP BY customer_age_group
               ORDER BY avg_order_value DESC;""")
Q2_results = cursor.fetchall()
Q2_results = pd.DataFrame(Q2_results, columns=['age_group','avg_order_value'])
Q2_results

      age_group  avg_order_value
0   Middle-Aged      1869.776234
1        Adults      1844.730721
2  Young Adults      1838.954584
3           NaN      1821.514801
4       Seniors      1820.397376

3. Weekend vs weekday order patterns

In [8]:
cursor.execute("""SELECT order_day, COUNT(order_id) AS total_orders,
               SUM(final_amount) AS revenue
               FROM food_delivery_db.delivery_table
               GROUP BY order_day 
               ORDER BY revenue DESC;""")
Q3_results = cursor.fetchall()
Q3_results = pd.DataFrame(Q3_results, columns=['order_day','total_orders','revenue'])
Q3_results

  order_day  total_orders     revenue
0   Weekday         23348  43110815.0
1   Weekend          9338  17314271.5

4. Monthly revenue trends

In [9]:
cursor.execute("""SELECT YEAR(order_date) AS year, MONTH(order_date) AS month,
               SUM(final_amount) AS revenue, avg(final_amount) AS avg_amount
               FROM food_delivery_db.delivery_table
               GROUP BY year, month
               ORDER BY year, month ;""")
Q4_results = cursor.fetchall()
Q4_results =pd.DataFrame(Q4_results, columns = ['year', 'month', 'revenue','avg_amount'] )
Q4_results

    year  month    revenue   avg_amount
0   2024      1  5184619.5  1832.021025
1   2024      2  4877001.5  1846.649565
2   2024      3  5120757.5  1839.352550
3   2024      4  4817886.0  1850.186636
4   2024      5  5025218.0  1861.191852
5   2024      6  5186954.0  1838.693371
6   2024      7  5552205.0  1884.658859
7   2024      8  4880444.0  1829.937758
8   2024      9  4924189.5  1850.503382
9   2024     10  4998872.5  1846.646657
10  2024     11  4847151.0  1831.186626
11  2024     12  5009788.0  1870.719940

5. Impact of discounts on profit

In [36]:
cursor.execute("""SELECT discount_applied,
               ROUND(AVG(profit_margin_percentage), 2) AS avg_profit_margin,
               ROUND(SUM(final_amount), 2) AS revenue
               FROM food_delivery_db.delivery_table
               GROUP BY discount_applied
               ORDER BY discount_applied;""")
Q5_results = cursor.fetchall()
Q5_results = pd.DataFrame(Q5_results, columns = ['discount_applied', 'profit_margin_percentage', 'revenue'])
Q5_results

   discount_applied  profit_margin_percentage     revenue
0               0.0                      0.02  10658973.5
1              20.0                      0.02  10159708.5
2              35.0                      0.03     25773.0
3              50.0                      0.02  20377647.5
4              75.0                      0.05     40281.0
5             100.0                      0.02  10302246.5
6             220.0                      0.02   8860456.5

6. High-revenue cities and cuisines

In [11]:
cursor.execute("""SELECT city,cuisine_type,
               SUM(final_amount) AS total_revenue
               FROM food_delivery_db.delivery_table
               GROUP BY city, cuisine_type
               ORDER BY total_revenue DESC;""")
Q6_results = cursor.fetchall()
Q6_results = pd.DataFrame(Q6_results,columns=['city', 'cuisine_type', 'total_revenue'])
Q6_results

         city cuisine_type  total_revenue
0   Hyderabad       Indian      6702208.5
1   Hyderabad      Mexican      3491074.5
2   Hyderabad      Italian      3467016.0
3   Hyderabad      Arabian      3443770.5
4   Bangalore       Indian      3378686.5
5     Chennai       Indian      3372480.0
6   Hyderabad      Chinese      3321427.0
7       Delhi       Indian      3315522.0
8      Mumbai       Indian      3296539.0
9   Bangalore      Chinese      1760763.0
10  Bangalore      Mexican      1740961.0
11    Chennai      Chinese      1738376.0
12     Mumbai      Chinese      1736599.5
13      Delhi      Chinese      1720168.5
14    Chennai      Italian      1695758.5
15     Mumbai      Arabian      1668308.5
16  Bangalore      Arabian      1664272.0
17  Bangalore      Italian      1660107.5
18     Mumbai      Italian      1636037.0
19    Chennai      Arabian      1625890.0
20      Delhi      Italian      1622301.0
21      Delhi      Arabian      1607046.5
22     Mumbai      Mexican      1605983.0
23    Chennai      Mexican      1581722.0
24      Delhi      Mexican      1572068.5

7. Average delivery time by city

In [12]:
cursor.execute("""SELECT city,AVG(delivery_time_min) AS avg_delivery_time
               FROM food_delivery_db.delivery_table
               GROUP BY city
               ORDER BY avg_delivery_time DESC;""")
Q7_results = cursor.fetchall()
Q7_results = pd.DataFrame(Q7_results,columns = ['city', 'avg_delivery_time'])
Q7_results

        city avg_delivery_time
0     Mumbai          122.8247
1      Delhi          121.2296
2  Hyderabad          119.8651
3  Bangalore          119.5620
4    Chennai          119.2998

8. Distance vs delivery delay analysis

In [13]:
cursor.execute("""SELECT
               ROUND((distance_km),0) AS distance_km, 
               round(AVG(delivery_time_min),2) AS avg_delivery_time
               FROM food_delivery_db.delivery_table
               GROUP BY distance_km
               ORDER BY avg_delivery_time
               DESC;""")
Q8_results = cursor.fetchall()
Q8_results = pd. DataFrame(Q8_results, columns = ['distance_km','avg_delivery_time'])
Q8_results

      distance_km avg_delivery_time
0            27.0            296.00
1            16.0            291.00
2            19.0            290.00
3            30.0            287.00
4            35.0            284.00
...           ...               ...
4006         36.0             26.33
4007         26.0             25.00
4008          7.0             25.00
4009         38.0             25.00
4010         30.0             23.00

[4011 rows x 2 columns]

9. Delivery rating vs delivery time

In [14]:
cursor.execute("""SELECT 
               delivery_rating,
               COUNT(*) AS total_orders,
               AVG(delivery_time_min) AS delivery_time
               FROM food_delivery_db.delivery_table
               GROUP BY delivery_rating
               ORDER BY delivery_rating DESC;""")
Q9_results = cursor.fetchall()
Q9_results = pd.DataFrame( Q9_results, columns=['delivery_rating', 'total_orders', 'delivery_time'])
Q9_results

   delivery_rating  total_orders delivery_time
0                5          4593      121.1132
1                4          4876      122.1411
2                3          8698      120.3072
3                2          4904      120.3134
4                1          4646      119.5801
5                0          4969      119.2747

10. Top-rated restaurants

In [15]:
cursor.execute("""SELECT
               restaurant_name, AVG(restaurant_rating) AS avg_rating,
               COUNT(order_id) AS total_orders
               FROM food_delivery_db.delivery_table
               GROUP BY restaurant_name
               ORDER BY avg_rating DESC, total_orders DESC limit 10;""")
Q10_results = cursor.fetchall()
Q10_results = pd.DataFrame(Q10_results, columns=['restaurant_name', 'avg_rating', 'total_orders'])
Q10_results

  restaurant_name  avg_rating  total_orders
0  Restaurant_352    4.483636            55
1  Restaurant_487    4.428814            59
2  Restaurant_173    4.408333            72
3  Restaurant_446    4.404938            81
4  Restaurant_496    4.404615            65
5   Restaurant_55    4.402899            69
6  Restaurant_447    4.397101            69
7  Restaurant_134    4.396078            51
8  Restaurant_150    4.390625            64
9  Restaurant_355    4.389552            67

11. Cancellation rate by restaurant

In [16]:
cursor.execute(""" SELECT  restaurant_name, 
               COUNT(*) AS total_orders, 
               SUM(CASE WHEN order_status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_orders,
               ROUND(SUM(CASE WHEN order_status = 'Cancelled' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS cancellation_rate
               FROM food_delivery_db.delivery_table
               GROUP BY restaurant_name
               ORDER BY cancellation_rate DESC limit 10;""")
Q11_results = cursor.fetchall()
Q11_results = pd.DataFrame(Q11_results,columns=['restaurant_name', 'total_orders', 'cancelled_orders', 'cancellation_rate'])
Q11_results

  restaurant_name  total_orders cancelled_orders cancellation_rate
0  Restaurant_455            53               18             33.96
1  Restaurant_494            64               19             29.69
2  Restaurant_250            62               18             29.03
3  Restaurant_290            45               13             28.89
4  Restaurant_126            55               15             27.27
5  Restaurant_281            59               16             27.12
6  Restaurant_113            56               15             26.79
7  Restaurant_496            65               17             26.15
8  Restaurant_426            73               19             26.03
9   Restaurant_85            58               15             25.86

12. Cuisine-wise performance

In [17]:
cursor.execute("""SELECT cuisine_type,
               COUNT(order_id) AS total_orders,
               ROUND(AVG(final_amount), 2) AS avg_order_value,
               ROUND(SUM(final_amount), 2) AS total_revenue,
               ROUND(AVG(restaurant_rating), 2) AS avg_rating,
               AVG(profit_margin_percentage) AS avg_profit_margin
               FROM food_delivery_db.delivery_table
               GROUP BY cuisine_type
               ORDER BY total_revenue DESC;""")
Q12_results = cursor.fetchall()
Q12_results = pd.DataFrame(Q12_results, columns=['cuisine', 'total_orders', 'avg_order_value','total_revenue', 'avg_rating','avg_profit_margin'])
Q12_results

,cuisine,total_orders,avg_order_value,total_revenue,avg_rating,avg_profit_margin
0,Indian,10921,1837.33,20065436.0,4.20,0.020791
1,Chinese,5495,1870.31,10277334.0,4.19,0.018638
2,Italian,5446,1851.12,10081220.0,4.22,0.018717
3,Arabian,5447,1837.58,10009287.5,4.19,0.023517
4,Mexican,5377,1858.25,9991809.0,4.19,0.013662

13. Peak hour demand analysis

In [18]:
cursor.execute("""SELECT
               peak_hour, COUNT(order_id) AS total_orders,
               ROUND(SUM(final_amount), 2) AS total_revenue
               FROM food_delivery_db.delivery_table
               GROUP BY peak_hour
               ORDER BY total_orders DESC""")
Q13_results = cursor.fetchall()
Q13_results = pd.DataFrame(Q13_results,columns=['peak_hour', 'total_orders', 'total_revenue'])
Q13_results

   peak_hour  total_orders  total_revenue
0          0         16344     30189393.5
1          1         16342     30235693.0

14. Payment mode preferences

In [19]:
cursor.execute("""SELECT
               payment_mode,
               COUNT(order_id) AS total_orders,
               ROUND(SUM(final_amount), 2) AS total_revenue
               FROM food_delivery_db.delivery_table
               GROUP BY payment_mode
               ORDER BY total_orders DESC;""")
Q14_results = cursor.fetchall()
Q14_results = pd.DataFrame(Q14_results, columns=['payment_mode', 'total_orders', 'total_revenue'])
Q14_results

  payment_mode  total_orders  total_revenue
0         Card         13149     24206504.0
1       Wallet          6590     12136184.0
2          UPI          6507     11995444.0
3          COD          6440     12086954.5

15. Cancellation reason analysis

In [20]:
cursor.execute("""SELECT
               cancellation_reason,
               COUNT(order_id) AS total_cancellations
               FROM food_delivery_db.delivery_table
               WHERE order_status = 'Cancelled'
               GROUP BY cancellation_reason
               ORDER BY total_cancellations DESC;""")
Q15_results = cursor.fetchall()
Q15_results = pd.DataFrame(Q15_results, columns=['cancellation_reason', 'total_cancellations'])
Q15_results

  cancellation_reason  total_cancellations
0       Late Delivery                 2972
1  Customer Cancelled                 1013
2    Restaurant Issue                  984

DASHBORAD KPI

1. TOTAL ORDERS

In [21]:
cursor.execute("""SELECT COUNT(order_id) AS total_orders FROM food_Delivery_db.delivery_table;""")
total_orders = cursor.fetchall()
total_orders = pd.DataFrame(total_orders, columns = ['total_orders'])
total_orders

   total_orders
0         32686

2. TOTAL REVENUE

In [22]:
cursor.execute("""SELECT  SUM(final_amount) AS total_revenue FROM food_Delivery_db.delivery_table;""")
total_revenue = cursor.fetchall()
total_revenue = pd.DataFrame(total_revenue, columns = ['total_revenue'])
total_revenue

   total_revenue
0     60425086.5

3. AVERAGE ORDER VALUE

In [23]:
cursor.execute("""SELECT  ROUND(AVG(final_amount),2) AS avg_order_value FROM food_Delivery_db.delivery_table;""")
avg_order_value = cursor.fetchall()
avg_order_value = pd.DataFrame(avg_order_value, columns = ['avg_order_value'])
avg_order_value

   avg_order_value
0          1848.65

4. AVERAGE DELIVERY TIME

In [24]:
cursor.execute("""SELECT ROUND(AVG(delivery_time_min),2) AS avg_delivery_time FROM food_Delivery_db.delivery_table;""")
avg_delivery_time = cursor.fetchall()
avg_delivery_time = pd.DataFrame(avg_delivery_time, columns = ['avg_delivery_time'])
avg_delivery_time

  avg_delivery_time
0            120.43

5. CANCELLATION RATE

In [25]:
cursor.execute("""SELECT  ROUND(SUM(CASE WHEN order_status = 'Cancelled' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),2) 
               AS cancellation_rate
               FROM food_Delivery_db.delivery_table;""")
cancellation_rate = cursor.fetchall()
cancellation_rate = pd.DataFrame(cancellation_rate, columns = ['cancellation_rate'])
cancellation_rate

  cancellation_rate
0             15.20

6. AVERAGE DELIVERY RATING

In [26]:
cursor.execute("""SELECT  ROUND(AVG(delivery_rating), 2) AS avg_delivery_rating
               FROM food_Delivery_db.delivery_table;""")
avg_delivery_rating = cursor.fetchall()
avg_delivery_rating = pd.DataFrame(avg_delivery_rating, columns = ['avg_delivery_rating'])
avg_delivery_rating

  avg_delivery_rating
0                2.54

7. PROFIT MARGIN PERCENTAGE

In [27]:
cursor.execute("""SELECT ROUND(AVG(profit_margin_percentage), 2) AS profit_margin_percentage
               FROM food_Delivery_db.delivery_table;""")
profit_margin_percentage = cursor.fetchall()
profit_margin_percentage = pd.DataFrame(profit_margin_percentage, columns = ['profit_margin %'])
profit_margin_percentage

   profit_margin %
0             0.02

FETCHING ALL DASHBOARD KPI

In [28]:
cursor.execute(""" SELECT
               COUNT(order_id) AS total_orders,
               SUM(final_amount) AS total_revenue,   
               ROUND(AVG(final_amount),2) AS avg_order_value,
               ROUND(AVG(delivery_time_min),2) AS avg_delivery_time,
               ROUND(SUM(CASE WHEN order_status = 'Cancelled' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),2) AS cancellation_rate,
               ROUND(AVG(delivery_rating), 2) AS avg_delivery_rating,
               ROUND(AVG(profit_margin_percentage), 2) AS profit_margin_percentage
               FROM food_delivery_db.delivery_table; """)

dashboard_kpi = cursor.fetchall()

dashboard_kpi = pd.DataFrame(dashboard_kpi, columns=['total_orders','total_revenue',
                                                     'avg_order_value', 'avg_delivery_time',
                                                     'cancellation_rate','avg_delivery_rating',
                                                     'profit_margin%'])

dashboard_kpi

,total_orders,total_revenue,avg_order_value,avg_delivery_time,cancellation_rate,avg_delivery_rating,profit_margin%
0,32686,60425086.5,1848.65,120.43,15.20,2.54,0.02